name: Install uwit-iam/common-build-scripts
description: >
  Installs the common-build-scripts into the github workspace in the
  `./build-scripts` directory.

inputs:
  version:
    required: true
    default: latest
    description: >
      Supply the version you'd like to install; default is 'latest'.
      Only versions 0.1.1 or greater are supported.

runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/entrypoint.sh --version ${{ inputs.version }}
