on:
  release:
    types:
      - published

env:
  image: ghcr.io/uwit-iam/common-build-scripts

jobs:
  tag-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          version=$(basename $GITHUB_REF)
          docker pull $image:$version
          docker tag $image:$version $image:latest
          docker tag $image:$version $image:release
          docker push $image:latest
          docker push $image:release
