name: Test use docker image with action

on:
  push:
    branches:
      - test-run-as-action

jobs:
  test-run-as-action:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/uwit-iam/common-build-scripts:latest
