name: Test actions/install
on:
  push:
    branches:
      - test-install-action

jobs:
  test-install-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uwit-iam/common-build-scripts/install-action@test-install-action
      - run: test -d ./.build-scripts/sources
